### ISSUE TITLE
Citrine Demo Not Working After Recent Changes

### ISSUE THREAD

**Issue by louisg1337** [EVerest/everest-demo#50]
After the #39 changes were merged into main, the Citrine demo using SP1 no longer works. All the software loads properly and runs, but once we get into the SIL simulation, EVerest is unable to connect to the websocket. I even tried connecting EVerest to Citrine's `8081` port which is unsecured, yet it still is unable to connect.

**To Reproduce**
- Broken Demo
  - Clone `main` from https://github.com/EVerest/everest-demo
  - Run `bash ./demo-iso15118-2-ac-plus-ocpp.sh -c -1`
- Older Working Demo
  - Clone https://github.com/louisg1337/everest-demo/, and checkout `citrine_demo`
  - Run `bash ./demo-iso15118-2-ac-plus-ocpp.sh -c -1`
  
**Hardware**
MacBook - macOS Ventura: 13.6.7 - Intel Core i7

**Comment by shankari** [comment]
The error is 

```
2024-06-04 22:47:20.503637 [INFO] ocpp:OCPP201     :: Reconnecting to plain websocket at uri: ws://localhost:9000/cp001 with security profile: 1
```

It seems like the device_model is not being copied properly or is invalid...

**Comment by shankari** [comment]
There are three databases in here

```
# find / -name \*device_model_storage.db\*
/ext/source/build/_deps/libocpp-build/config/v201/device_model_storage.db
/ext/source/build/dist/share/everest/modules/OCPP201/device_model_storage.db
/workspace/dist/share/everest/modules/OCPP201/device_model_storage.db
```

The one in `dist/share/everest/modules/OCPP201/device_model_storage.db` has the correct URL

```
# sqlite3 dist/share/everest/modules/OCPP201/device_model_storage.db
sqlite> select * from VARIABLE_ATTRIBUTE;
22|22|2|1|0|0|[{"configurationSlot": 1, "connectionData": {"messageTimeout": 30, "ocppCsmsUrl": "ws://host.docker.internal/ws/cp001", "ocppInterface": "Wired0", "ocppTransport": "JSON", "ocppVersion": "OCPP20", "securityProfile": 1}}]
```

The one in `/ext/source/build/dist/share/everest/modules/OCPP201/device_model_storage.db` has the wrong one

```
# sqlite3 /ext/source/build/dist/share/everest/modules/OCPP201/device_model_storage.db
sqlite> select * from VARIABLE_ATTRIBUTE;
35|35|2|1|0|0|[{"configurationSlot": 1, "connectionData": {"messageTimeout": 30, "ocppCsmsUrl": "ws://localhost:9000/cp001", "ocppInterface": "Wired0", "ocppTransport": "JSON", "ocppVersion": "OCPP20", "securityProfile": 1}}]
```

Given that this is working for MaEVe, I wonder if we are not copying the device model over properly
